# PHP7.2 + drush + composer
image: registry.gitlab.com/tuutti/drupal-php-docker:7.2

before_script:
- ./.gitlab-ci/setup.sh

services:
- mariadb:latest

variables:
  SYMFONY_DEPRECATIONS_HELPER: disabled
  DRUPAL_MODULE_NAME: commerce_paytrail
  DRUPAL_SERVER_HOST: http://127.0.0.1
  DRUPAL_SERVER_PORT: 8080
  DRUPAL_CORE: 8.8.x
  DRUPAL_INSTALL_PROFILE: minimal
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal
  SIMPLETEST_DB: mysql://root:drupal@mariadb/drupal

test:mysql:
  script:
    - php ~/drupal/core/scripts/run-tests.sh --verbose --color --url "$DRUPAL_SERVER_HOST:$DRUPAL_SERVER_PORT" $DRUPAL_MODULE_NAME
