commerce_payment.commerce_payment_gateway.plugin.paytrail:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    merchant_hash:
      type: string
      label: 'Merchant Authentication Hash'
    culture:
      type: string
      label: 'Language'
    included_data:
      type: mapping
      mapping:
        payer:
          type: string
        product:
          type: string
    bypass_mode:
      type: boolean
      label: 'Bypass mode'
    allow_ipn_create_payment:
      type: boolean
      label: 'Allow IPN to create payments'
