commerce_payment.commerce_payment_gateway.plugin.paytrail:
  type: commerce_payment_gateway_configuration
  mapping:
    language:
      type: string
      label: 'Language'
    account:
      type: string
      label: 'Merchant ID'
    secret:
      type: string
      label: 'Secret'
    collect_billing_information:
      type: boolean
      label: 'Collect billing information'

