commerce_payment.commerce_payment_gateway.plugin.paytrail:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    merchant_hash:
      type: string
      label: 'Merchant Authentication Hash'
    culture:
      type: string
      label: 'Language'
    paytrail_mode:
      type: string
      label: 'Mode'
    paytrail_type:
      type: string
      label: 'Type'
    visible_methods:
      type: sequence
      label: 'Visible payment methods'
      sequence:
        type: string
