commerce_paytrail.paytrail_payment_method.*:
  type: config_entity
  label: 'Payment method config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    adminLabel:
      type: label
      label: 'Administrator label'
    uuid:
      type: string
